<?php

namespace App\Modules\IdentityCore\Catalog;

/**
 * Default tenant roles, permission bundles, and SoD pairs.
 * Bootstrap skips missing permission codes and feature-gated roles without entitlement.
 */
final class DefaultRoleCatalog
{
    public static function roles(): array
    {
        $identityBase = [
            'identity.profile.view',
            'identity.profile.update',
            'identity.user.view',
        ];

        $orgView = [
            'organization.company.view',
            'organization.branch.view',
            'organization.department.view',
        ];

        return [
            [
                'code' => 'group-identity',
                'name' => 'هویت و دسترسی',
                'description' => 'گروه نقش‌های مدیریت هویت',
                'parent_code' => null,
                'is_group' => true,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => null,
                'permission_codes' => [],
            ],
            [
                'code' => 'group-organization',
                'name' => 'ساختار سازمانی',
                'description' => 'گروه نقش‌های سازمان',
                'parent_code' => null,
                'is_group' => true,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => null,
                'permission_codes' => [],
            ],
            [
                'code' => 'group-finance',
                'name' => 'مالی و حسابداری',
                'description' => 'گروه نقش‌های مالی',
                'parent_code' => null,
                'is_group' => true,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'accounting.',
                'permission_codes' => [],
            ],
            [
                'code' => 'group-sales',
                'name' => 'فروش',
                'description' => 'گروه نقش‌های فروش',
                'parent_code' => null,
                'is_group' => true,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'procurement.sales',
                'permission_codes' => [],
            ],
            [
                'code' => 'group-purchase',
                'name' => 'خرید',
                'description' => 'گروه نقش‌های خرید',
                'parent_code' => null,
                'is_group' => true,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'procurement.purchase',
                'permission_codes' => [],
            ],
            [
                'code' => 'group-inventory',
                'name' => 'انبار و موجودی',
                'description' => 'گروه نقش‌های انبار',
                'parent_code' => null,
                'is_group' => true,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'inventory.',
                'permission_codes' => [],
            ],
            [
                'code' => 'identity-manager',
                'name' => 'مدیر هویت و دسترسی',
                'description' => 'مدیریت کاربران، نقش‌ها، مجوزها، محدوده، SoD و بازبینی دسترسی',
                'parent_code' => 'group-identity',
                'is_group' => false,
                'is_privileged' => true,
                'required_feature' => null,
                'required_any_permission_prefix' => 'identity.',
                'permission_codes' => array_merge($identityBase, [
                    'identity.user.create', 'identity.user.update', 'identity.user.delete',
                    'identity.role.view', 'identity.role.create', 'identity.role.update', 'identity.role.delete',
                    'identity.role.assign', 'identity.role.assign-permissions',
                    'identity.permission.view',
                    'identity.scope.view', 'identity.scope.create', 'identity.scope.update', 'identity.scope.delete', 'identity.scope.assign',
                    'identity.membership_history.view',
                    'identity.sod.view', 'identity.sod.manage',
                    'identity.mfa.manage',
                    'identity.access_cert.view', 'identity.access_cert.manage', 'identity.access_cert.certify',
                ]),
            ],
            [
                'code' => 'identity-members',
                'name' => 'کارشناس اعضای سازمان',
                'description' => 'افزودن و مدیریت وضعیت اعضا بدون مدیریت نقش‌ها',
                'parent_code' => 'group-identity',
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'identity.',
                'permission_codes' => array_merge($identityBase, [
                    'identity.user.create', 'identity.user.update',
                    'identity.membership_history.view',
                ]),
            ],
            [
                'code' => 'identity-roles',
                'name' => 'کارشناس نقش‌ها',
                'description' => 'تعریف نقش و تخصیص مجوز',
                'parent_code' => 'group-identity',
                'is_group' => false,
                'is_privileged' => true,
                'required_feature' => null,
                'required_any_permission_prefix' => 'identity.',
                'permission_codes' => array_merge($identityBase, [
                    'identity.role.view', 'identity.role.create', 'identity.role.update',
                    'identity.role.assign', 'identity.role.assign-permissions',
                    'identity.permission.view', 'identity.sod.view',
                ]),
            ],
            [
                'code' => 'access-certifier',
                'name' => 'بازبین دسترسی',
                'description' => 'تصمیم‌گیری روی کمپین بازبینی دسترسی',
                'parent_code' => 'group-identity',
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'identity.access_cert',
                'permission_codes' => array_merge($identityBase, [
                    'identity.access_cert.view', 'identity.access_cert.certify',
                    'identity.role.view', 'identity.membership_history.view',
                ]),
            ],
            [
                'code' => 'org-admin',
                'name' => 'مدیر ساختار سازمانی',
                'description' => 'مدیریت شرکت، شعبه، واحد و سلسله‌مراتب',
                'parent_code' => 'group-organization',
                'is_group' => false,
                'is_privileged' => true,
                'required_feature' => null,
                'required_any_permission_prefix' => 'organization.',
                'permission_codes' => array_merge($identityBase, $orgView, [
                    'organization.company.create', 'organization.company.update', 'organization.company.delete',
                    'organization.branch.create', 'organization.branch.update', 'organization.branch.delete',
                    'organization.department.create', 'organization.department.update', 'organization.department.delete',
                    'organization.ownership.view', 'organization.ownership.manage',
                    'organization.fiscal.view', 'organization.fiscal.manage',
                    'organization.bank.view', 'organization.bank.manage',
                    'organization.officer.view', 'organization.officer.manage',
                    'organization.business_unit.view', 'organization.business_unit.manage',
                    'organization.cost_center.view', 'organization.cost_center.manage',
                    'organization.hierarchy.view', 'organization.hierarchy.manage',
                    'organization.sales_org.view', 'organization.sales_org.manage',
                    'organization.purch_org.view', 'organization.purch_org.manage',
                    'organization.sales_structure.view', 'organization.sales_structure.manage',
                    'organization.intercompany.view', 'organization.intercompany.manage',
                    'organization.structure.configure',
                ]),
            ],
            [
                'code' => 'org-viewer',
                'name' => 'مشاهده‌گر سازمان',
                'description' => 'فقط مشاهده ساختار سازمانی',
                'parent_code' => 'group-organization',
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'organization.',
                'permission_codes' => array_merge($identityBase, $orgView, [
                    'organization.hierarchy.view',
                    'organization.business_unit.view',
                    'organization.cost_center.view',
                ]),
            ],
            [
                'code' => 'org-multi-company',
                'name' => 'مدیر چندشرکتی',
                'description' => 'نیازمند بسته multi_company',
                'parent_code' => 'group-organization',
                'is_group' => false,
                'is_privileged' => true,
                'required_feature' => 'multi_company',
                'required_any_permission_prefix' => 'organization.company',
                'permission_codes' => array_merge($identityBase, $orgView, [
                    'organization.company.create', 'organization.company.update',
                    'organization.ownership.view', 'organization.ownership.manage',
                    'organization.intercompany.view', 'organization.intercompany.manage',
                    'organization.consolidation.view', 'organization.consolidation.manage',
                ]),
            ],
            [
                'code' => 'finance-manager',
                'name' => 'مدیر مالی',
                'description' => 'نظارت مالی',
                'parent_code' => 'group-finance',
                'is_group' => false,
                'is_privileged' => true,
                'required_feature' => null,
                'required_any_permission_prefix' => 'accounting.',
                'permission_codes' => array_merge($identityBase, [
                    'accounting.voucher.view', 'accounting.voucher.post', 'accounting.account.view',
                    'procurement.payment-schedule.view',
                    'procurement.cash-transaction.view', 'procurement.cash-transaction.create',
                    'procurement.sales-invoice.view', 'procurement.purchase-invoice.view',
                ]),
            ],
            [
                'code' => 'accountant',
                'name' => 'حسابدار',
                'description' => 'ثبت و مشاهده اسناد',
                'parent_code' => 'group-finance',
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'accounting.',
                'permission_codes' => array_merge($identityBase, [
                    'accounting.voucher.view', 'accounting.account.view',
                ]),
            ],
            [
                'code' => 'accountant-senior',
                'name' => 'حسابدار ارشد',
                'description' => 'ثبت و قطعی‌سازی اسناد',
                'parent_code' => 'group-finance',
                'is_group' => false,
                'is_privileged' => true,
                'required_feature' => null,
                'required_any_permission_prefix' => 'accounting.',
                'permission_codes' => array_merge($identityBase, [
                    'accounting.voucher.view', 'accounting.voucher.post', 'accounting.account.view',
                ]),
            ],
            [
                'code' => 'cashier',
                'name' => 'صندوقدار',
                'description' => 'تراکنش‌های نقدی',
                'parent_code' => 'group-finance',
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'procurement.cash',
                'permission_codes' => array_merge($identityBase, [
                    'procurement.cash-transaction.view', 'procurement.cash-transaction.create',
                    'procurement.payment-schedule.view',
                ]),
            ],
            [
                'code' => 'sales',
                'name' => 'کارشناس فروش',
                'description' => 'سفارش و فاکتور فروش',
                'parent_code' => 'group-sales',
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'procurement.sales',
                'permission_codes' => array_merge($identityBase, [
                    'procurement.sales-order.create', 'procurement.sales-order.view', 'procurement.sales-order.confirm',
                    'procurement.sales-invoice.view', 'procurement.sales-invoice.create',
                ]),
            ],
            [
                'code' => 'sales-lead',
                'name' => 'سرپرست فروش',
                'description' => 'نظارت فروش',
                'parent_code' => 'group-sales',
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'procurement.sales',
                'permission_codes' => array_merge($identityBase, [
                    'procurement.sales-order.create', 'procurement.sales-order.view', 'procurement.sales-order.confirm',
                    'procurement.sales-invoice.view', 'procurement.sales-invoice.create', 'procurement.sales-invoice.post',
                ]),
            ],
            [
                'code' => 'purchase',
                'name' => 'کارشناس خرید',
                'description' => 'سفارش خرید و رسید',
                'parent_code' => 'group-purchase',
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'procurement.purchase',
                'permission_codes' => array_merge($identityBase, [
                    'procurement.purchase-order.create',
                    'procurement.purchase-receipt.create', 'procurement.purchase-receipt.view', 'procurement.purchase-receipt.post',
                    'procurement.purchase-requisition.view', 'procurement.purchase-requisition.create',
                ]),
            ],
            [
                'code' => 'purchase-manager',
                'name' => 'مدیر خرید',
                'description' => 'نظارت خرید',
                'parent_code' => 'group-purchase',
                'is_group' => false,
                'is_privileged' => true,
                'required_feature' => null,
                'required_any_permission_prefix' => 'procurement.purchase',
                'permission_codes' => array_merge($identityBase, [
                    'procurement.purchase-order.create',
                    'procurement.purchase-receipt.create', 'procurement.purchase-receipt.view', 'procurement.purchase-receipt.post',
                    'procurement.purchase-requisition.view', 'procurement.purchase-requisition.create',
                    'procurement.purchase-invoice.view',
                ]),
            ],
            [
                'code' => 'warehouse',
                'name' => 'انباردار',
                'description' => 'کالا و اسناد موجودی',
                'parent_code' => 'group-inventory',
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'inventory.',
                'permission_codes' => array_merge($identityBase, [
                    'inventory.item.view', 'inventory.item.create',
                    'inventory.warehouse.view',
                    'inventory.document.view', 'inventory.document.create', 'inventory.document.post',
                ]),
            ],
            [
                'code' => 'warehouse-manager',
                'name' => 'مدیر انبار',
                'description' => 'نظارت انبار',
                'parent_code' => 'group-inventory',
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => 'inventory.',
                'permission_codes' => array_merge($identityBase, [
                    'inventory.item.view', 'inventory.item.create',
                    'inventory.warehouse.view',
                    'inventory.document.view', 'inventory.document.create', 'inventory.document.post',
                ]),
            ],
            [
                'code' => 'viewer',
                'name' => 'مشاهده‌گر عمومی',
                'description' => 'فقط مشاهده',
                'parent_code' => null,
                'is_group' => false,
                'is_privileged' => false,
                'required_feature' => null,
                'required_any_permission_prefix' => null,
                'permission_codes' => [
                    'identity.user.view', 'identity.role.view', 'identity.permission.view', 'identity.profile.view',
                    'organization.company.view', 'organization.branch.view', 'organization.department.view',
                ],
            ],
        ];
    }

    public static function sodRules(): array
    {
        return [
            [
                'code' => 'sod-accountant-purchase',
                'name' => 'حسابدار × کارشناس خرید',
                'description' => 'جداسازی ثبت مالی از خرید',
                'role_a_code' => 'accountant',
                'role_b_code' => 'purchase',
                'severity' => 3,
                'enforcement' => 'BLOCK',
            ],
            [
                'code' => 'sod-accountant-senior-purchase-manager',
                'name' => 'حسابدار ارشد × مدیر خرید',
                'description' => 'جداسازی قطعی اسناد از مدیریت خرید',
                'role_a_code' => 'accountant-senior',
                'role_b_code' => 'purchase-manager',
                'severity' => 4,
                'enforcement' => 'BLOCK',
            ],
            [
                'code' => 'sod-finance-manager-cashier',
                'name' => 'مدیر مالی × صندوقدار',
                'description' => 'نظارت مالی جدا از اجرای نقدی',
                'role_a_code' => 'finance-manager',
                'role_b_code' => 'cashier',
                'severity' => 3,
                'enforcement' => 'BLOCK',
            ],
            [
                'code' => 'sod-accountant-senior-cashier',
                'name' => 'حسابدار ارشد × صندوقدار',
                'description' => 'قطعی سند جدا از دریافت/پرداخت',
                'role_a_code' => 'accountant-senior',
                'role_b_code' => 'cashier',
                'severity' => 4,
                'enforcement' => 'BLOCK',
            ],
            [
                'code' => 'sod-sales-accountant-senior',
                'name' => 'کارشناس فروش × حسابدار ارشد',
                'description' => 'فاکتور فروش جدا از قطعی حسابداری',
                'role_a_code' => 'sales',
                'role_b_code' => 'accountant-senior',
                'severity' => 3,
                'enforcement' => 'BLOCK',
            ],
            [
                'code' => 'sod-sales-lead-finance-manager',
                'name' => 'سرپرست فروش × مدیر مالی',
                'description' => 'هشدار ترکیب نظارت فروش و مالی',
                'role_a_code' => 'sales-lead',
                'role_b_code' => 'finance-manager',
                'severity' => 2,
                'enforcement' => 'WARN',
            ],
            [
                'code' => 'sod-purchase-warehouse',
                'name' => 'کارشناس خرید × انباردار',
                'description' => 'خرید جدا از ثبت موجودی',
                'role_a_code' => 'purchase',
                'role_b_code' => 'warehouse',
                'severity' => 3,
                'enforcement' => 'BLOCK',
            ],
            [
                'code' => 'sod-purchase-manager-warehouse-manager',
                'name' => 'مدیر خرید × مدیر انبار',
                'description' => 'هشدار ترکیب مدیریت خرید و انبار',
                'role_a_code' => 'purchase-manager',
                'role_b_code' => 'warehouse-manager',
                'severity' => 2,
                'enforcement' => 'WARN',
            ],
            [
                'code' => 'sod-identity-manager-access-certifier',
                'name' => 'مدیر هویت × بازبین دسترسی',
                'description' => 'هشدار تجمع قدرت تخصیص و بازبینی',
                'role_a_code' => 'identity-manager',
                'role_b_code' => 'access-certifier',
                'severity' => 2,
                'enforcement' => 'WARN',
            ],
            [
                'code' => 'sod-identity-roles-identity-members',
                'name' => 'کارشناس نقش‌ها × کارشناس اعضا',
                'description' => 'هشدار تعریف نقش و ایجاد عضو',
                'role_a_code' => 'identity-roles',
                'role_b_code' => 'identity-members',
                'severity' => 2,
                'enforcement' => 'WARN',
            ],
            [
                'code' => 'sod-sales-purchase',
                'name' => 'کارشناس فروش × کارشناس خرید',
                'description' => 'هشدار ترکیب فروش و خرید',
                'role_a_code' => 'sales',
                'role_b_code' => 'purchase',
                'severity' => 2,
                'enforcement' => 'WARN',
            ],
        ];
    }
}
